language: bash
sudo: false

language: elixir

matrix:
  include:
    - elixir: 1.9.4
    - elixir: 1.10.4
      otp_release: 23.3.1
    - elixir: 1.11.4
      otp_release: 23.3.1

script:
  - "MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis"
